language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
branches:
  only:
  - master
before_script:
- npm install -g mocha
script:
- npm -d install
- npm test
after_success:
- wget https://s3.amazonaws.com/elasticbeanstalk/cli/AWS-ElasticBeanstalk-CLI-2.5.1.zip
- unzip AWS-ElasticBeanstalk-CLI-2.5.1.zip
- export PATH=$PATH:$PWD/AWS-ElasticBeanstalk-CLI-2.5.1/eb/linux/python2.7
- eb init | $AWS_ACCESS_KEY | $AWS_ACCESS_SECRET | 5 | mitb-node-demo | mitb-node-demo | 6 | 2 | n | 2 |
- eb start | y
- git clone https://github.com/andrewbeng89/mitb_node_demo.git
- cd mitb_node_demo
- git branch -a
- git checkout gh-pages
- ls
- git checkout master -- public
- git checkout master -- index.html
- git pull origin gh-pages
- git add ./public
- git add ./index.html
- git config --global user.email "andrew.beng.2010@sis.smu.edu.sg"
- git config --global user.name "andrewbeng89"
- git commit -a -m "travis-ci update"
- git status
- git push https://$MY_GITHUB_TOKEN@github.com/andrewbeng89/mitb_node_demo.git gh-pages
env:
  global:
  - secure: Zne2/PcxxbtCM6QCQehWVGpqcCZDIF1Z6MTRBfaL5OtHTptMEp//jI1v6BdTGSMOK2FkuUMofRjuTtS+6XkVSawi1j+vTpzm6AAPMcd4gT1rhJxWWy7UFuB+kxNE14SC3fOwvZC4i9Mt8nJVDftdHc/3sxryJ6DrMIbQRL3HgDk=
  - secure: TXoDGrBizugjfP8pqBoUbsxD9e/T7m8Y+dbDfjl8/1/1qW+yihH1l+uEl9/fSgVrWhx2GUYM4+80zHWlNLDYoKDHVz9H6spFLREb/Rdjzn9/RfR9uCOMnZIeqlgs7uDE0FnP1zxkwV96nqqoAwfbDuAS4f2MEtuXU1qSSDZxLxs=
  - secure: Z720libU/DM0EZcaBag0HiA8Lo5ZjXWhE1kF99FGOKvkxtzyZ2VbyD4VAzEjcbdfL/CQFp9irTZlE642g1p8psMb7vwQTyWFpOgexmVEstBvxMWjJkN5JRcx7X8qpGValc/LVcAdl6MySSAWqzJWetYCbVvdBVn7eP+l1uFhyGs=
deploy:
  provider: heroku
  api_key:
    secure: P9jpi9rk9W+564aOVRTu6z/VoFYBUH06AtqvQcs61JJ7TinDfuSKeWsSoG3TCfSLEEDDJ4ubKuezrXSYnDQ6PmFokRsBLCaoJeGOVhDq/OGSGjSGfwx1OlV//Aug7zEoSzWNh2wj4VFKvC/iPGiFgAG+v7lOvh0JQA4jE3zwGkw=
  app: mitb-node-demo
  on:
    repo: andrewbeng89/mitb_node_demo
